# Exercise 2.C Working with multiple DataFrames

In [1]:
import numpy as np
import pandas as pd

## Basic Aggregations

In [3]:
# Create a DataFrame named df_sales
data = {
    'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North'],
    'Units_Sold': [10, 15, 20, 5, 10, 15, 10, 5, 15],
    'Price': [100, 200, 150, 100, 200, 150, 100, 200, 150]
}

df_sales = pd.DataFrame(data)
df_sales

  Product Region  Units_Sold  Price
0       A  North          10    100
1       B  South          15    200
2       C   East          20    150
3       A   West           5    100
4       B  North          10    200
5       C  South          15    150
6       A   East          10    100
7       B   West           5    200
8       C  North          15    150

In [4]:
# Adding a new column Revenue by multiplying Units_Sold and Price
df_sales['Revenue'] = df_sales['Units_Sold'] * df_sales['Price']
df_sales

  Product Region  Units_Sold  Price  Revenue
0       A  North          10    100     1000
1       B  South          15    200     3000
2       C   East          20    150     3000
3       A   West           5    100      500
4       B  North          10    200     2000
5       C  South          15    150     2250
6       A   East          10    100     1000
7       B   West           5    200     1000
8       C  North          15    150     2250

In [6]:
# Calculating the total Units_Sold and total Revenue across all products and regions
total_units = df_sales['Units_Sold'].sum()
total_revenue = df_sales['Revenue'].sum()

print(f"Total Units Sold: {total_units}")
print(f"Total Revenue: {total_revenue}")

Total Units Sold: 105
Total Revenue: 16000

In [7]:
# Calculating the average Units_Sold and average Revenue
avg_units = df_sales['Units_Sold'].mean()
avg_revenue = df_sales['Revenue'].mean()

print(f"Average Units Sold: {avg_units}")
print(f"Average Revenue: {avg_revenue}")

Average Units Sold: 11.666666666666666
Average Revenue: 1777.7777777777778

## Grouping Data

In [8]:
# Grouping by Product and calculating the total Units_Sold and Revenue
product_totals = df_sales.groupby('Product')[['Units_Sold', 'Revenue']].sum()
product_totals

         Units_Sold  Revenue
Product
A                25     2500
B                30     6000
C                50     7500

In [9]:
# Grouping by Region and calculating the average Units_Sold and Revenue
region_averages = df_sales.groupby('Region')[['Units_Sold', 'Revenue']].mean()
region_averages

        Units_Sold  Revenue
Region
East     15.000000   2000.0
North    11.666667   1750.0
South    15.000000   2625.0
West      5.000000    750.0

In [10]:
# Grouping by both Product and Region to calculate the sum
combined_totals = df_sales.groupby(['Product', 'Region'])[['Units_Sold', 'Revenue']].sum()
combined_totals

                Units_Sold  Revenue
Product Region
A       East            10     1000
        North           10     1000
        West             5      500
B       North           10     2000
        South           15     3000
        West             5     1000
C       East            20     3000
        North           15     2250
        South           15     2250

## Sorting and Ranking Data

In [11]:
# Sort df_sales by Units_Sold in ascending order
df_sales.sort_values(by='Units_Sold', ascending=True)

  Product Region  Units_Sold  Price  Revenue
3       A   West           5    100      500
7       B   West           5    200     1000
0       A  North          10    100     1000
4       B  North          10    200     2000
6       A   East          10    100     1000
1       B  South          15    200     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
2       C   East          20    150     3000

In [12]:
# Sort df_sales by Revenue in descending order
df_sales.sort_values(by='Revenue', ascending=False)

  Product Region  Units_Sold  Price  Revenue
1       B  South          15    200     3000
2       C   East          20    150     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
7       B   West           5    200     1000
3       A   West           5    100      500

In [13]:
# Add a new column Revenue_Rank ranking the Revenue values in descending order
df_sales['Revenue_Rank'] = df_sales['Revenue'].rank(ascending=False)

In [14]:
# Call df_sales to review the changes
df_sales

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank
0       A  North          10    100     1000           7.0
1       B  South          15    200     3000           1.5
2       C   East          20    150     3000           1.5
3       A   West           5    100      500           9.0
4       B  North          10    200     2000           5.0
5       C  South          15    150     2250           3.5
6       A   East          10    100     1000           7.0
7       B   West           5    200     1000           7.0
8       C  North          15    150     2250           3.5

## Merging DataFrames

In [15]:
# Create a new DataFrame named df_products
product_data = {
    'Product': ['A', 'B', 'C'],
    'Category': ['Electronics', 'Furniture', 'Appliances']
}
df_products = pd.DataFrame(product_data)
df_products

  Product     Category
0       A  Electronics
1       B    Furniture
2       C   Appliances

In [16]:
# Merge df_sales with df_products on the Product column
df_merged = pd.merge(df_sales, df_products, on='Product')

In [17]:
# Call df_merged to review the merged DataFrame
df_merged

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank     Category
0       A  North          10    100     1000           7.0  Electronics
1       B  South          15    200     3000           1.5    Furniture
2       C   East          20    150     3000           1.5   Appliances
3       A   West           5    100      500           9.0  Electronics
4       B  North          10    200     2000           5.0    Furniture
5       C  South          15    150     2250           3.5   Appliances
6       A   East          10    100     1000           7.0  Electronics
7       B   West           5    200     1000           7.0    Furniture
8       C  North          15    150     2250           3.5   Appliances

In [18]:
# Group by Category to calculate the total Revenue
category_revenue = df_merged.groupby('Category')['Revenue'].sum()
category_revenue

Category
Appliances     7500
Electronics    2500
Furniture      6000
Name: Revenue, dtype: int64